# Generated by Django 3.0.8 on 2020-07-15 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classmate',
            fields=[
                ('cno', models.AutoField(primary_key=True, serialize=False)),
                ('clsname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('curno', models.AutoField(primary_key=True, serialize=False)),
                ('curname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=255)),
                ('cn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg.Classmate')),
                ('cour', models.ManyToManyField(to='reg.Course')),
            ],
        ),
    ]
